import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { ProductProvider } from "./context/ProductContext";
import ProductAlert from "./components/ProductAlert";
import { AuthProvider } from "./context/AuthContext";
import SideBar from "./components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bogi Shop 1.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  // https://e-commerce-api-8p0f.onrender.com
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <AuthProvider>
            <ProductProvider>
              <NavBar />
              <div className="mt-28"></div>
              {children}
              <ProductAlert />
              <div className="mb-28"></div>
            </ProductProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
