import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/NavBar";
import { ProductProvider } from "./context/ProductContext";
import AlertDialog from "../components/Alert";
import { AuthProvider } from "./context/AuthContext";
import Provider from "@components/SessionProvider";
import { GlobalProvider } from "./context/GlobalContext";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Bogi Shop 1.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  // https://e-commerce-api-8p0f.onrender.com
}>) {
  return (
    <html lang="en">
      <body className={cn("font-sans", fontSans.variable)}>
        <GlobalProvider>
          <AlertDialog />
          <Provider>
            <AuthProvider>
              <ProductProvider>
                <NavBar />
                <div className="container">{children}</div>
                <div className="footer mt-20">CPY BY BOJAN947</div>
              </ProductProvider>
            </AuthProvider>
          </Provider>
        </GlobalProvider>
      </body>
    </html>
  );
}
